import React, { useState } from "react";
import { CalendarBlank, BookOpenText, PencilSimpleLine, Graph, ChartBar, CloudArrowDown, ArrowRight, Check, CaretRight, CaretUp, Lightbulb, SealCheck, FloppyDisk, X } from "@phosphor-icons/react";
import "@fontsource/source-sans-3/400.css";
import "@fontsource/source-sans-3/600.css";
import "@fontsource/source-serif-4/400.css";
import "@fontsource/source-serif-4/600.css";
import "@fontsource/caveat/500.css";
import "@fontsource/caveat/600.css";
import "./handwriting.css";

const navItems = [[CalendarBlank,"Today"],[BookOpenText,"Lessons"],[PencilSimpleLine,"Practice"],[Graph,"Map"],[ChartBar,"Progress"]];

function StepRail({ checked }) {
  return <div className="step-rail" aria-label="Lesson progress">{["Understand","Watch","Solve","Reflect"].map((label,index)=><div className={`step ${index<2||(checked&&index===2)?"done":index===2?"active":""}`} key={label}><span className="step-dot">{index<2||(checked&&index===2)?<Check weight="bold"/>:index+1}</span><span>{label}</span></div>)}</div>;
}

function Sidebar({ active, setActive }) {
  return <aside className="sidebar"><div className="brand">Maths<br/>Studio<span/></div><nav aria-label="Primary navigation">{navItems.map(([Icon,label])=><button className={active===label?"nav-item active":"nav-item"} onClick={()=>setActive(label)} key={label}><Icon size={25} weight={active===label?"duotone":"regular"}/><span>{label}</span></button>)}</nav><div className="offline"><CloudArrowDown size={27}/><span>Downloaded<small>low data</small></span></div></aside>;
}

function TutorPanel({ tutorOpen, setTutorOpen, altExplanation, setAltExplanation }) {
  return <aside className={`right-panel ${tutorOpen?"":"collapsed"}`}><header className="tutor-title"><h2>AI Tutor</h2><button onClick={()=>setTutorOpen(!tutorOpen)}>{tutorOpen?"Hide":"Show"} <CaretUp/></button></header>{tutorOpen&&<><section className="tutor-note"><div className="note-kicker"><span>2</span> Let’s think about line 2.</div><p>{altExplanation?"Imagine an equal balance: taking 5 away from only one tray would tip it. What must you do to the other tray?":"Why do we subtract 5 from 20 on the right-hand side when we subtract 5 from the left?"}</p><button onClick={()=>setAltExplanation(!altExplanation)}>Explain another way <ArrowRight/></button></section><section className="progress-panel"><div className="section-head"><h3>My progress</h3><button>See all</button></div><div className="mastery-line"><span>Exploring</span><ArrowRight/><strong>Developing</strong></div><div className="progress-track"><span/></div><div className="evidence"><p>Evidence of learning</p><span><Check/> Kept both sides equal</span><span><Check/> Removed the constant</span></div><div className="next-skill"><p>Next skill</p><strong>Isolate the variable term</strong><span>Divide both sides by 3</span></div></section><section className="continue-panel"><h3>Continue learning</h3><button><PencilSimpleLine/> Practice set: Level 2 <CaretRight/></button><button><Graph/> Open Knowledge Map <CaretRight/></button><p className="map-label">Knowledge map preview</p><div className="map-preview" aria-label="Algebra concept connections"><div className="map-node">Algebra<br/>Basics</div><ArrowRight/><div className="map-node current">Linear<br/>Equations</div><ArrowRight/><div className="map-node">Simultaneous<br/>Equations</div></div></section></>}</aside>;
}

export function App() {
  const [active,setActive]=useState("Lessons");
  const [operation,setOperation]=useState("Subtract 5 from both sides");
  const [checked,setChecked]=useState(false);
  const [tutorOpen,setTutorOpen]=useState(true);
  const [altExplanation,setAltExplanation]=useState(false);
  return <main className="app-shell"><Sidebar active={active} setActive={setActive}/><section className="workspace"><header className="lesson-header"><div className="breadcrumbs">Lessons <CaretRight/> Algebra <CaretRight/> Linear Equations <CaretRight/> <span>Solving by Balancing</span></div><div className="lesson-title-row"><div><h1>Solving Linear Equations</h1><p>Solve for x: <strong>3x + 5 = 20</strong></p></div><StepRail checked={checked}/></div></header><section className="worked-example"><span className="hand-label">Worked example</span><div className="example-flow"><b>3x + 5 = 20</b><em>Subtract 5<br/>from both sides</em><ArrowRight/><b>3x + 5 − 5 = 20 − 5</b><ArrowRight/><b>3x = 15</b><em>Divide both<br/>sides by 3</em><ArrowRight/><b>x = 5</b></div></section><section className="notebook"><div className="notebook-top"><div><span className="hand-label">Your step</span><p>Apply the operation to both sides. Keep the equation balanced.</p></div><select value={operation} onChange={(e)=>{setOperation(e.target.value);setChecked(false)}}><option>Subtract 5 from both sides</option><option>Add 5 to both sides</option><option>Divide both sides by 3</option></select></div><div className="equation-lines"><div className="line-number">1</div><div className="equation">3x + 5 = 20</div><div className="annotation red">Starting equation</div><div className={`line-number ${checked?"success":""}`}>2</div><div className={`equation input-line ${checked?"checked":""}`}>3x + 5 <span>− 5</span> = 20 <span>− 5</span><i/></div><div className="annotation green">{checked?"Correct — the same operation was applied to both sides.":"Apply the same operation to both sides."}</div><div className="line-number">3</div><div className="equation muted">3x = 15</div><div className="annotation">Simplify both sides</div><div className="line-number">4</div><div className="equation fraction-row"><span><u>3x</u><u>3</u></span> = <span><u>15</u><u>3</u></span></div><div className="annotation">Divide both sides by 3</div><div className="line-number">5</div><div className="equation muted">x = 5</div><div className="annotation">Solution</div></div><div className="notebook-footer"><button className="hint-button" onClick={()=>setTutorOpen(true)}><Lightbulb/> Need a hint?</button><button className="check-button" onClick={()=>setChecked(true)}>{checked?<><Check weight="bold"/> Reasoning checked</>:<>Check my reasoning <ArrowRight/></>}</button><div className="craft-actions"><SealCheck size={64} weight="duotone"/><button><FloppyDisk/> Save best solution</button></div></div>{checked&&<div className="success-toast"><Check weight="bold"/> Nice work. You kept the equation balanced.<button onClick={()=>setChecked(false)} aria-label="Dismiss"><X/></button></div>}</section></section><TutorPanel tutorOpen={tutorOpen} setTutorOpen={setTutorOpen} altExplanation={altExplanation} setAltExplanation={setAltExplanation}/></main>;
}
