#!/usr/bin/env tsx
/**
 * Generate missing lessons and question banks via the OpenAI API.
 * Resumes safely: existing files are skipped unless --force is passed, and
 * hand-authored files are never overwritten even then.
 *
 *   npx tsx scripts/content-generate.ts
 *   npx tsx scripts/content-generate.ts --subject accounting
 *   npx tsx scripts/content-generate.ts --programme bsc-computer-science --year Year1
 *   npx tsx scripts/content-generate.ts --limit 2 --questions 10
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { lessonSchema, questionFileSchema, type Lesson, type Question, type QuestionFile, type Subject, type Subtopic, type Topic } from "../lib/content/schema";
import { TIER_REQUIREMENTS } from "../lib/content/validate";
import { buildContentIndex, idSlug } from "../lib/content/loader";

const SUBJECTS_DIR = path.join(process.cwd(), "content/subjects");
/** Secondary subjects whose notation needs LaTeX and the stronger model. */
const QUANTITATIVE = new Set(["sec.mathematics", "sec.physics", "sec.chemistry", "sec.accounting", "sec.economics"]);

/**
 * Every file this script writes carries this source id. The `--force` guard
 * keys off it so hand-authored content is never regenerated (see shouldSkip).
 */
const GENERATED_SOURCE_ID = "openai-curriculum-pack";

interface GeneratedPayload {
  lessonTitle?: string;
  estimatedMinutes?: number;
  blocks?: unknown[];
  questions?: unknown[];
}

function loadEnvLocal(): void {
  const file = path.join(process.cwd(), ".env.local");
  if (!existsSync(file)) return;
  for (const line of readFileSync(file, "utf8").split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#") || !trimmed.includes("=")) continue;
    const eq = trimmed.indexOf("=");
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if ((value.startsWith("\"") && value.endsWith("\"")) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    if (!process.env[key]) process.env[key] = value;
  }
}

function argValue(flag: string): string | undefined {
  const index = process.argv.indexOf(flag);
  if (index === -1) return undefined;
  return process.argv[index + 1];
}

function hasFlag(flag: string): boolean {
  return process.argv.includes(flag);
}

const SECONDARY_PROVENANCE = {
  sources: [{ id: GENERATED_SOURCE_ID, title: "Mindspark OpenAI curriculum pack", type: "authored" as const }],
  reviewStatus: "published" as const,
  verified: false,
  note: "Exam-pattern content generated with OpenAI against the WAEC/NECO/JAMB syllabus. Not a verbatim past paper.",
};

const UNDERGRADUATE_PROVENANCE = {
  sources: [{ id: GENERATED_SOURCE_ID, title: "Mindspark OpenAI curriculum pack", type: "authored" as const }],
  reviewStatus: "published" as const,
  verified: false,
  note: "Authored with OpenAI against the international undergraduate consensus core (the courses MIT, Cambridge and Imperial all teach). Synthesised, not transcribed from any institution's materials.",
};

/**
 * Everything that used to be hardcoded to Nigerian secondary school. A profile
 * is resolved per subject so a university course and a JSS1 subject can be
 * generated by the same pipeline without either compromising the other.
 *
 * Note that `latex` and `model` are separate: the old QUANTITATIVE set decided
 * both at once, which is why undergraduate CS was generated on the cheap model
 * *and* told not to use LaTeX, despite being dense with asymptotic notation.
 */
interface SubjectProfile {
  model: string;
  latex: boolean;
  /** Inclusive block count range for a lesson, as prompt copy. */
  blockRange: string;
  minutesCap: number;
  minQuestions: number;
  voice: "secondary" | "undergraduate";
  defaultBoard: "WAEC" | "internal";
  provenance: typeof SECONDARY_PROVENANCE;
}

/** Per-subject escape hatch. Empty by default — the level defaults are the contract. */
const PROFILE_OVERRIDES: Record<string, Partial<SubjectProfile>> = {};

function profileFor(subject: Subject): SubjectProfile {
  const tierMin = TIER_REQUIREMENTS.find((requirement) => requirement.subjectId === subject.id)?.minQuestionsPerSubtopic;
  const strongModel = process.env.OPENAI_CONTENT_MODEL_STRICT ?? "gpt-4o";
  const baseModel = process.env.OPENAI_CONTENT_MODEL ?? "gpt-4o-mini";

  const base: SubjectProfile =
    subject.level === "undergraduate"
      ? {
          model: strongModel,
          latex: true,
          blockRange: "12–16",
          minutesCap: 24,
          minQuestions: tierMin ?? 8,
          voice: "undergraduate",
          defaultBoard: "internal",
          provenance: UNDERGRADUATE_PROVENANCE,
        }
      : {
          model: QUANTITATIVE.has(subject.id) ? strongModel : baseModel,
          latex: QUANTITATIVE.has(subject.id),
          blockRange: "8–11",
          minutesCap: 18,
          minQuestions: tierMin ?? 5,
          voice: "secondary",
          defaultBoard: "WAEC",
          provenance: SECONDARY_PROVENANCE,
        };

  return { ...base, ...PROFILE_OVERRIDES[subject.id] };
}

async function sleep(ms: number): Promise<void> {
  await new Promise((resolve) => setTimeout(resolve, ms));
}

const MAX_ATTEMPTS = 8;

/**
 * OpenAI reserves `max_tokens` against the per-minute token budget whether or
 * not the completion uses it. Measured across 291 generated units, output is
 * ~3k tokens median and ~8.3k at p90 — so reserving 12k throttled a 30k TPM
 * account to roughly two requests a minute. An occasional truncation is cheaper
 * than that: it fails JSON parsing and the existing retry regenerates.
 */
const MAX_OUTPUT_TOKENS = Number(process.env.OPENAI_MAX_OUTPUT_TOKENS ?? "8000");

/** Honour the server's own backoff hint before falling back to exponential. */
function retryDelayMs(response: Response, body: string, attempt: number): number {
  const header = Number(response.headers.get("retry-after-ms"));
  if (Number.isFinite(header) && header > 0) return header + 250;
  const seconds = Number(response.headers.get("retry-after"));
  if (Number.isFinite(seconds) && seconds > 0) return seconds * 1000 + 250;
  const stated = body.match(/try again in ([\d.]+)s/);
  if (stated) return Number(stated[1]) * 1000 + 250;
  return Math.min(4000 * 2 ** (attempt - 1), 60_000);
}

async function chatJson(model: string, system: string, user: string, attempt: number): Promise<GeneratedPayload> {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) throw new Error("OPENAI_API_KEY is not set. Add it to app-web/.env.local");

  let response: Response;
  try {
    response = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      signal: AbortSignal.timeout(240_000),
      body: JSON.stringify({
        model,
        temperature: attempt === 1 ? 0.4 : 0.2,
        max_tokens: MAX_OUTPUT_TOKENS,
        response_format: { type: "json_object" },
        messages: [
          { role: "system", content: system },
          { role: "user", content: user },
        ],
      }),
    });
  } catch (error) {
    /**
     * A dropped connection or timeout rejects the fetch rather than returning a
     * status, so it bypassed the 429/5xx handling below entirely — which is why
     * a concurrency-10 run failed 406 of 437 units with a bare "fetch failed".
     */
    if (attempt < MAX_ATTEMPTS) {
      await sleep(Math.min(4000 * 2 ** (attempt - 1), 60_000));
      return chatJson(model, system, user, attempt + 1);
    }
    const cause = (error as { cause?: { code?: string; message?: string } }).cause;
    throw new Error(
      `network error after ${MAX_ATTEMPTS} attempts: ${(error as Error).message}${cause?.code ? ` (${cause.code})` : ""}`,
    );
  }

  if (!response.ok) {
    const body = await response.text();
    if ((response.status === 429 || response.status >= 500) && attempt < MAX_ATTEMPTS) {
      await sleep(retryDelayMs(response, body, attempt));
      return chatJson(model, system, user, attempt + 1);
    }
    throw new Error(`OpenAI ${response.status}: ${body.slice(0, 300)}`);
  }

  const data = (await response.json()) as { choices?: Array<{ message?: { content?: string } }> };
  const content = data.choices?.[0]?.message?.content;
  if (!content) throw new Error("OpenAI returned an empty completion");
  return JSON.parse(content) as GeneratedPayload;
}

/** Rules that hold for every level — schema shape, not pedagogy. */
const STRUCTURAL_RULES = `- Return ONE JSON object with keys: lessonTitle, estimatedMinutes, blocks, questions.
- Never invent image/video/interactive blocks. Never use type "image", "video" or "interactive".
- Include exactly one check block: { "type": "check", "questionId": "q001" }.
- hook.text ≥ 20 chars. text.markdown ≥ 20 chars. summary.points ≥ 2.
- callout.variant is one of: definition, key-point, warning, example, exam-tip.
- worked_example must have title, prompt, steps (≥2 objects {text, latex?}), answer.
- table must have headers (array of strings) and rows (array of arrays of strings, one per row, each the same length as headers), plus an optional caption. Every cell is a string, so write numbers as strings: {"type":"table","headers":["Algorithm","Best","Worst"],"rows":[["Merge sort","$O(n \\\\log n)$","$O(n \\\\log n)$"],["Quicksort","$O(n \\\\log n)$","$O(n^2)$"]]}.
- options MUST be an array of objects [{ "id": "a", "text": "..." }, ...], never a keyed object.
- Every callout MUST include variant, title and text. Every worked_example MUST include title, prompt, steps and answer.
- Every mcq needs correctOptionId, correctOptionText and distractorRationale for every wrong option.
- correctOptionText MUST be the exact text of the correct option, copied verbatim from your own options array. Work out the answer FIRST, then find which option holds it, then write both the letter and that option's text. The letter, the text and the value your explanation derives must all agree.
- Distractors must be plausible mistakes a real student would make, never jokes or filler.
- Every question MUST include an explanation of at least two sentences that teaches the reasoning.
- No duplicate stems.
- Do not invent IDs except questionId "q001" on the check block.`;

const LATEX_RULE =
  '- Use $...$ for inline maths in markdown/stems. Use math blocks {type:"math", latex, caption?} for displayed formulae. Escape JSON backslashes (\\\\frac).';

function systemPrompt(subject: Subject, profile: SubjectProfile): string {
  if (profile.voice === "undergraduate") {
    return `You author undergraduate university course content for Mindspark.

The standard is the international consensus core — the material that MIT, Cambridge, Imperial and Berkeley all teach in this course. Write at genuine university level: correct, rigorous, and quantitative.

How to teach (this matters as much as correctness):
- Build from intuition to formalism. Open with the physical or computational idea, then give the formal statement, then use it.
- Assume no prior exposure to THIS topic, but do assume the prerequisites of the year level.
- A student must be able to learn this unit from the lesson alone, with no lecturer. If a step would lose them, show the step.
- Define every symbol at first use. State units. Name the assumptions a result depends on.
- Prefer a concrete worked case over an abstract statement.

Lesson shape:
- ${profile.blockRange} blocks. Use the full palette: hook → text → callout(definition) → math → worked_example → table → text → worked_example → list → callout(key-point or warning) → summary.
- Include AT LEAST ONE table block. Nearly every unit has something to tabulate, and a table teaches a comparison far better than a paragraph: algorithm complexities, material properties, load cases, method trade-offs, protocol layers, test types, failure modes, when-to-use-which. Find the comparison in this unit and tabulate it. Only omit the table if the unit genuinely contains nothing comparable.
- Include at least two worked_example blocks with full step-by-step reasoning.
- Use math blocks for any displayed equation. Do not write equations as plain text.

${STRUCTURAL_RULES}

Assessment — this mirrors how these courses are really examined (problem sets and written papers, not multiple choice):
- Aim for roughly 50% mcq, 25% numeric, 25% theory. A true_false is acceptable occasionally in place of an mcq.
- numeric questions MUST have correctValue (a number), a tolerance (a positive number generous enough to accept a sensibly rounded answer, e.g. correctValue 9.81 with tolerance 0.05), and state the expected unit in the stem.
- theory questions MUST have a markingGuide: an array of the specific points a marker awards credit for. Write them so a human could mark against them.
- Numeric and theory questions should read like problem-set or exam questions: give real values with units and ask for a derived quantity or a justified argument.
- Difficulty mix: ~30% 1, ~50% 2, ~20% 3.
- Set board to "internal" on every question. This is university coursework, not a national exam board.
- Never reference WAEC, NECO, JAMB, or Nigerian secondary school. Use SI units and international engineering/CS conventions.

${LATEX_RULE}`;
  }

  return `You author Nigerian senior-secondary learning content for Mindspark.

Hard rules:
- Factually correct and aligned to WAEC, NECO, JAMB and NERDC.
- Use Nigerian names, naira, markets, WAEC/NECO/JAMB phrasing where natural.
- Lessons: ${profile.blockRange} blocks. Recommended shape: hook → text → callout(definition) → text/table/list → worked_example → text → callout(exam-tip) → summary.
${STRUCTURAL_RULES}
- Questions: mostly mcq with 4 options a–d. You may include 1 true_false (options a=True, b=False) and 1 theory (with markingGuide array) if it fits.
- exam-pattern only. Do not claim a real past-paper year.
- Difficulty mix: ~30% 1, ~50% 2, ~20% 3.
- board: spread across WAEC, NECO, JAMB.
${profile.latex ? LATEX_RULE : "- Do not force LaTeX. Plain clear English is better."}
- Teach, do not dump notes. A student should be able to learn the subtopic from the lesson alone.`;
}

function userPrompt(
  subject: Subject,
  topic: Topic,
  subtopic: Subtopic,
  minQuestions: number,
  profile: SubjectProfile,
  errors?: string,
): string {
  const objectives = subtopic.objectives.map((objective) => `- ${objective.id}: ${objective.text}`).join("\n");

  const heading =
    profile.voice === "undergraduate"
      ? `Course: ${subject.courseCode ? `${subject.courseCode} ` : ""}${subject.name} (${subject.id})
Year: ${topic.classLevels.join(", ")}${subject.semester ? ` · Semester ${subject.semester}` : ""}
Module: ${topic.name} (${topic.id})
Module summary: ${topic.summary}
Unit: ${subtopic.name} (${subtopic.id})
Unit summary: ${subtopic.summary}
Pitch this at the stated year of the degree: rigorous, but do not assume material from later years.`
      : `Subject: ${subject.name} (${subject.id})
Level: ${subject.level}
Curricula: ${subject.curricula.join(", ")}
Topic: ${topic.name} (${topic.id})
Topic class levels: ${topic.classLevels.join(", ")}
Topic summary: ${topic.summary}
Subtopic: ${subtopic.name} (${subtopic.id})
Subtopic summary: ${subtopic.summary}
Write ONLY at this class level. A JSS1 learner must not get SS3 material, and an SS3 learner must not get JSS1 material.`;

  const unitWord = profile.voice === "undergraduate" ? "unit" : "subtopic";

  return `${heading}
Learning objectives:
${objectives}

Write one lesson and exactly ${minQuestions + 2} questions for THIS ${unitWord} only (extras are kept as a buffer).
Questions must assess the objectives above.
Every question needs a full explanation of at least two sentences.
${errors ? `\nThe previous draft failed validation. Fix every issue:\n${errors}` : ""}`;
}

function asRecord(value: unknown): Record<string, unknown> {
  return value && typeof value === "object" ? (value as Record<string, unknown>) : {};
}

/**
 * A numeric answer key is useless without a tolerance: gradeAnswer defaults it
 * to 0, so a student typing a correctly-rounded 9.8 against a key of 9.81 is
 * marked wrong. Honour the model's tolerance when it gives a sane one, and
 * otherwise allow 0.5% of the magnitude.
 */
function numericTolerance(raw: unknown, correctValue: unknown, type: string): number | undefined {
  if (type !== "numeric") return undefined;
  const provided = Number(raw);
  if (Number.isFinite(provided) && provided > 0) return provided;
  const value = Number(correctValue);
  if (!Number.isFinite(value)) return undefined;
  return Math.max(Math.abs(value) * 0.005, 1e-9);
}

/** Numeric tokens in a string, commas stripped, for cross-checking an answer key. */
function numbersIn(text: string): Set<string> {
  return new Set(text.replace(/,/g, "").match(/\d+(?:\.\d+)?/g) ?? []);
}

/**
 * Numbers an explanation presents as a computed result — those after "=" or "≈".
 * Matching every number in the prose misfires on figures the explanation merely
 * mentions ("the other 90% is lost as heat").
 */
function resultNumbersIn(text: string): Set<string> {
  const results = new Set<string>();
  for (const match of text.replace(/,/g, "").matchAll(/[=≈]\s*[^\d\n]{0,12}?(\d+(?:\.\d+)?)/g)) {
    results.add(match[1]!);
  }
  return results;
}

/**
 * The model computes the right value in its explanation but frequently keys the
 * wrong option letter — measured at 1 in 4 quantitative MCQs, which would mark a
 * correct student answer wrong. Two defences:
 *
 *   1. Prefer `correctOptionText` (the verbatim option text) over the letter,
 *      which removes the mis-indexing failure entirely.
 *   2. Where the option text is numeric, cross-check against the explanation and
 *      re-key to the option the explanation actually supports.
 *
 * Returns the resolved option id, or undefined when the evidence is ambiguous —
 * the caller drops the question, which triggers a regeneration attempt.
 */
function resolveCorrectOptionId(
  row: Record<string, unknown>,
  options: Question["options"],
  explanation: string,
): string | undefined {
  const stated = typeof row.correctOptionId === "string" ? row.correctOptionId : undefined;
  if (!options || options.length === 0) return stated;

  const text = typeof row.correctOptionText === "string" ? row.correctOptionText.trim().toLowerCase() : "";
  if (text) {
    const byText = options.find((option) => option.text.trim().toLowerCase() === text);
    if (byText) return byText.id;
  }

  const keyed = options.find((option) => option.id === stated);
  if (!keyed) return stated;

  const keyNumbers = numbersIn(keyed.text);
  const results = resultNumbersIn(explanation);
  if (keyNumbers.size === 0 || results.size === 0) return stated;
  if ([...keyNumbers].some((n) => results.has(n))) return stated;

  const supported = options.filter(
    (option) => option.id !== stated && [...numbersIn(option.text)].some((n) => results.has(n)),
  );
  if (supported.length === 1) return supported[0]!.id;
  return supported.length === 0 ? stated : undefined;
}

function normalizeOptions(value: unknown): Question["options"] {
  if (Array.isArray(value)) {
    return value.map((entry, index) => {
      const row = asRecord(entry);
      const fallbackId = String.fromCharCode(97 + index);
      return {
        id: typeof row.id === "string" && /^[a-h]$/.test(row.id) ? row.id : fallbackId,
        text: String(row.text ?? row.label ?? entry ?? ""),
      };
    });
  }
  if (value && typeof value === "object") {
    return Object.entries(value as Record<string, unknown>).map(([key, text], index) => ({
      id: /^[a-h]$/.test(key) ? key : String.fromCharCode(97 + index),
      text: typeof text === "string" ? text : String(asRecord(text).text ?? text ?? ""),
    }));
  }
  return undefined;
}

function normalizeDistractorRationale(
  value: unknown,
  options: Question["options"],
): Record<string, string> | undefined {
  if (!value) return undefined;
  if (Array.isArray(value)) {
    const mapped: Record<string, string> = {};
    value.forEach((entry, index) => {
      if (typeof entry === "string") {
        const option = options?.[index];
        const id = option && option.id !== undefined ? option.id : String.fromCharCode(97 + index);
        mapped[id] = entry;
        return;
      }
      const row = asRecord(entry);
      const id = typeof row.id === "string" ? row.id : typeof row.optionId === "string" ? row.optionId : String.fromCharCode(97 + index);
      mapped[id] = String(row.text ?? row.reason ?? row.rationale ?? "");
    });
    return Object.keys(mapped).length > 0 ? mapped : undefined;
  }
  if (typeof value === "object") {
    const mapped: Record<string, string> = {};
    for (const [key, text] of Object.entries(value as Record<string, unknown>)) {
      mapped[key] = typeof text === "string" ? text : String(asRecord(text).text ?? text ?? "");
    }
    return mapped;
  }
  return undefined;
}

function normalizeBlocks(blocks: unknown[]): unknown[] {
  return blocks.flatMap((block) => {
    const row = asRecord(block);
    if (row.type === "table") {
      /**
       * Tables were the one block type with no normaliser and no shape in the
       * prompt, and appeared in only 4% of generated undergraduate lessons
       * against 63% of secondary ones. Salvage the shapes the model actually
       * produces — rows as objects keyed by header, or cells as numbers —
       * rather than discarding a table that is nearly right.
       */
      let headers = Array.isArray(row.headers) ? row.headers.map((cell) => String(cell)) : [];
      const rawRows = Array.isArray(row.rows) ? row.rows : [];

      // Rows given as objects: derive headers from the first row when absent.
      if (headers.length === 0 && rawRows.length > 0 && !Array.isArray(rawRows[0]) && typeof rawRows[0] === "object") {
        headers = Object.keys(asRecord(rawRows[0])).map((key) => String(key));
      }

      const rows = rawRows
        .map((line) => {
          if (Array.isArray(line)) return line.map((cell) => String(cell ?? ""));
          const record = asRecord(line);
          if (Object.keys(record).length === 0) return [];
          return headers.map((header) => String(record[header] ?? ""));
        })
        .filter((line) => line.length > 0);

      if (headers.length === 0 || rows.length === 0) return [];
      // The schema requires every row to match the header count.
      const width = headers.length;
      const padded = rows.map((line) =>
        line.length === width ? line : [...line, ...Array(Math.max(0, width - line.length)).fill("")].slice(0, width),
      );
      return [{ type: "table", headers, rows: padded, ...(row.caption ? { caption: String(row.caption) } : {}) }];
    }
    if (row.type === "callout") {
      return [{
        type: "callout",
        variant: row.variant,
        title: String(row.title || row.variant || "Note"),
        text: String(row.text ?? row.body ?? ""),
      }];
    }
    if (row.type === "worked_example") {
      const steps = Array.isArray(row.steps)
        ? row.steps.map((step) => {
            if (typeof step === "string") return { text: step };
            const item = asRecord(step);
            return { text: String(item.text ?? item.step ?? ""), latex: typeof item.latex === "string" ? item.latex : undefined };
          })
        : [];
      return [{
        type: "worked_example",
        title: String(row.title || "Worked example"),
        prompt: String(row.prompt ?? row.question ?? ""),
        steps,
        answer: String(row.answer ?? row.result ?? ""),
      }];
    }
    if (row.type === "list") {
      const items = Array.isArray(row.items) ? row.items.map((item) => String(item)) : [];
      return [{ type: "list", style: row.style === "number" ? "number" : "bullet", items }];
    }
    if (row.type === "hook") {
      return [{ type: "hook", text: String(row.text ?? row.markdown ?? "") }];
    }
    if (row.type === "summary") {
      const points = Array.isArray(row.points) ? row.points.map((point) => String(point)) : [];
      return [{ type: "summary", points }];
    }
    return [block];
  });
}

const BOARDS = new Set(["WAEC", "NECO", "JAMB", "NERDC", "internal"]);

function assemble(
  raw: GeneratedPayload,
  subject: Subject,
  subtopic: Subtopic,
  minQuestions: number,
  profile: SubjectProfile,
): { lesson: Lesson; file: QuestionFile } {
  const questionsIn = Array.isArray(raw.questions) ? raw.questions : [];
  const questions: Question[] = questionsIn.map((entry, index) => {
    const row = asRecord(entry);
    const id = `${subtopic.id}.q${String(index + 1).padStart(3, "0")}`;
    const type = typeof row.type === "string" ? row.type : "mcq";
    /** Undergraduate coursework is "internal"; the old code coerced everything to WAEC. */
    const board = typeof row.board === "string" && BOARDS.has(row.board) ? row.board : profile.defaultBoard;
    const objectiveIds = subtopic.objectives.map((objective) => objective.id);
    const assigned = Array.isArray(row.objectiveIds)
      ? (row.objectiveIds as string[]).filter((id) => objectiveIds.includes(id))
      : [];
    const options = normalizeOptions(row.options);
    const statedOptionId = typeof row.correctOptionId === "string" ? row.correctOptionId : undefined;
    const distractorRationale = normalizeDistractorRationale(row.distractorRationale, options);
    let explanation = String(row.explanation ?? "").trim();
    if (explanation.length < 20) {
      const correctText = options?.find((option) => option.id === statedOptionId)?.text;
      const reasons = distractorRationale ? Object.values(distractorRationale).join(" ") : "";
      explanation = [correctText ? `The correct answer is ${correctText}.` : "", reasons].filter(Boolean).join(" ").trim();
    }
    if (explanation.length < 20) {
      explanation = `This answer is correct for ${subtopic.name} because it matches the syllabus definition; the other options mix up related but different ideas.`;
    }
    const correctOptionId = resolveCorrectOptionId(row, options, explanation);
    return {
      id,
      subtopicId: subtopic.id,
      objectiveIds: assigned.length > 0 ? assigned : [objectiveIds[index % objectiveIds.length]],
      /**
       * A "numeric" question whose answer is a word ("float") is ungradable —
       * gradeAnswer does Number(correctValue), gets NaN, and marks every answer
       * wrong. Reclassify it as the short_answer it actually is.
       */
      type: type === "numeric" && !Number.isFinite(Number(row.correctValue)) ? "short_answer" : type,
      difficulty: row.difficulty === 2 || row.difficulty === 3 ? row.difficulty : 1,
      stem: String(row.stem ?? ""),
      options,
      correctOptionId,
      correctOptionIds: Array.isArray(row.correctOptionIds) ? (row.correctOptionIds as string[]) : undefined,
      correctValue: row.correctValue as Question["correctValue"],
      /**
       * Without this, gradeAnswer falls back to a tolerance of 0 and marks a
       * correctly-rounded answer wrong (9.8 against a key of 9.81). Derive a
       * default from the magnitude when the model omits one.
       */
      tolerance: numericTolerance(row.tolerance, row.correctValue, type),
      markingGuide: Array.isArray(row.markingGuide) ? (row.markingGuide as string[]) : undefined,
      explanation,
      distractorRationale,
      misconceptionTags: Array.isArray(row.misconceptionTags) ? (row.misconceptionTags as string[]) : [],
      examMeta: { board, style: "exam-pattern" },
      provenance: profile.provenance,
    } as Question;
  }).filter((question) => {
    if (question.type === "mcq") return (question.options?.length ?? 0) >= 3 && Boolean(question.correctOptionId);
    if (question.type === "true_false") return (question.options?.length ?? 0) === 2;
    if (question.type === "theory") return (question.markingGuide?.length ?? 0) > 0;
    /** Drop before schema parse so one malformed numeric does not burn a retry on the whole file. */
    if (question.type === "numeric" || question.type === "short_answer") return question.correctValue !== undefined;
    return question.stem.length >= 5 && question.explanation.length >= 20;
  });

  if (questions.length < minQuestions) {
    throw new Error(`Only ${questions.length} usable questions, need ${minQuestions}`);
  }
  questions.splice(minQuestions + 2); // keep a small surplus, drop a huge overflow
  questions.forEach((question, index) => {
    question.id = `${subtopic.id}.q${String(index + 1).padStart(3, "0")}`;
  });

  let blocks = Array.isArray(raw.blocks) ? normalizeBlocks(raw.blocks) : [];
  const checkId = `${subtopic.id}.q001`;
  let sawCheck = false;
  blocks = blocks.map((block) => {
    const row = asRecord(block);
    if (row.type === "check") {
      sawCheck = true;
      return { type: "check", questionId: checkId };
    }
    if (row.type === "image" || row.type === "video" || row.type === "interactive") {
      return {
        type: "text",
        markdown: typeof row.fallbackText === "string" && row.fallbackText.length >= 20
          ? row.fallbackText
          : typeof row.alt === "string" && row.alt.length >= 20
            ? row.alt
            : "See the worked example and summary in this lesson for the key idea.",
      };
    }
    return block;
  });
  if (!sawCheck) {
    const summaryAt = blocks.findIndex((block) => asRecord(block).type === "summary");
    const check = { type: "check", questionId: checkId };
    if (summaryAt === -1) blocks.push(check);
    else blocks.splice(summaryAt, 0, check);
  }

  /**
   * MathText treats "$" as a maths delimiter, so an odd count in any block
   * string renders the rest of the paragraph as an unclosed formula. A guard
   * test already fails the build on this; catching it here instead turns it
   * into a regeneration attempt rather than a broken lesson on disk.
   */
  const unpaired = blocks.flatMap((block) => {
    const row = asRecord(block);
    const strings = [row.text, row.markdown, row.title, row.prompt, row.answer]
      .filter((value): value is string => typeof value === "string")
      .concat(Array.isArray(row.points) ? (row.points as string[]) : [])
      .concat(Array.isArray(row.steps) ? (row.steps as Array<{ text?: string }>).map((s) => s?.text ?? "") : []);
    return strings.filter((value) => (value.match(/\$/g) ?? []).length % 2 !== 0);
  });
  if (unpaired.length > 0) {
    throw new Error(`Unpaired "$" in lesson text (write currency as "one million dollars"): ${unpaired[0]!.slice(0, 90)}`);
  }

  const lesson: Lesson = {
    id: `${subtopic.id}.lesson`,
    subtopicId: subtopic.id,
    title: String(raw.lessonTitle || subtopic.name),
    estimatedMinutes: Number(raw.estimatedMinutes) > 0 ? Math.min(Number(raw.estimatedMinutes), profile.minutesCap) : 12,
    objectiveIds: subtopic.objectives.map((objective) => objective.id),
    blocks: blocks as Lesson["blocks"],
    provenance: profile.provenance,
  };

  return {
    lesson,
    file: { subtopicId: subtopic.id, questions },
  };
}

function formatZod(error: { issues: Array<{ path: (string | number)[]; message: string }> }): string {
  return error.issues.map((issue) => `${issue.path.join(".") || "(root)"}: ${issue.message}`).join("\n");
}

/**
 * True when a file exists and was NOT written by this script. `--force` must
 * never regenerate hand-authored content — the 24 authored undergraduate CS
 * lessons are the highest-quality content in the repo.
 */
function isHandAuthored(file: string): boolean {
  if (!existsSync(file)) return false;
  try {
    const parsed = JSON.parse(readFileSync(file, "utf8")) as {
      provenance?: { sources?: Array<{ id?: string }> };
      questions?: Array<{ provenance?: { sources?: Array<{ id?: string }> } }>;
    };
    const sources = parsed.provenance?.sources ?? parsed.questions?.[0]?.provenance?.sources ?? [];
    return !sources.some((source) => source.id === GENERATED_SOURCE_ID);
  } catch {
    return true; // unreadable: refuse to overwrite
  }
}

async function generateOne(
  subject: Subject,
  topic: Topic,
  subtopic: Subtopic,
  destDir: string,
  force: boolean,
  questionOverride?: number,
): Promise<"wrote" | "skipped" | "protected"> {
  const topicSlug = idSlug(topic.id);
  const subSlug = idSlug(subtopic.id);
  const folder = path.join(destDir, "topics", topicSlug);
  const lessonPath = path.join(folder, `${subSlug}.lesson.json`);
  const questionsPath = path.join(folder, `${subSlug}.questions.json`);
  if (!force && existsSync(lessonPath) && existsSync(questionsPath)) return "skipped";
  if (force && (isHandAuthored(lessonPath) || isHandAuthored(questionsPath))) return "protected";

  mkdirSync(folder, { recursive: true });
  const profile = profileFor(subject);
  const minQuestions = questionOverride && questionOverride > 0 ? questionOverride : profile.minQuestions;
  const model = profile.model;
  let errors: string | undefined;

  for (let attempt = 1; attempt <= 3; attempt += 1) {
    const raw = await chatJson(
      model,
      systemPrompt(subject, profile),
      userPrompt(subject, topic, subtopic, minQuestions, profile, errors),
      1,
    );
    try {
      const assembled = assemble(raw, subject, subtopic, minQuestions, profile);
      const lessonParsed = lessonSchema.safeParse(assembled.lesson);
      const questionsParsed = questionFileSchema.safeParse(assembled.file);
      if (!lessonParsed.success || !questionsParsed.success) {
        const parts: string[] = [];
        if (!lessonParsed.success) parts.push(`LESSON\n${formatZod(lessonParsed.error)}`);
        if (!questionsParsed.success) parts.push(`QUESTIONS\n${formatZod(questionsParsed.error)}`);
        throw new Error(parts.join("\n"));
      }
      writeFileSync(lessonPath, `${JSON.stringify(lessonParsed.data, null, 2)}\n`);
      writeFileSync(questionsPath, `${JSON.stringify(questionsParsed.data, null, 2)}\n`);
      return "wrote";
    } catch (error) {
      errors = error instanceof Error ? error.message : String(error);
      if (attempt === 3) throw new Error(`${subtopic.id}: ${errors}`);
    }
  }
  throw new Error(`${subtopic.id}: exhausted retries`);
}

async function mapPool<T, R>(items: T[], concurrency: number, worker: (item: T, index: number) => Promise<R>): Promise<R[]> {
  const results: R[] = new Array(items.length);
  let next = 0;
  async function run(): Promise<void> {
    while (next < items.length) {
      const index = next;
      next += 1;
      results[index] = await worker(items[index], index);
    }
  }
  await Promise.all(Array.from({ length: Math.min(concurrency, items.length) }, () => run()));
  return results;
}

async function main(): Promise<void> {
  loadEnvLocal();
  const only = argValue("--subject");
  const programme = argValue("--programme");
  const year = argValue("--year");
  const questionOverride = Number(argValue("--questions") ?? "0");
  const limit = Number(argValue("--limit") ?? "0");
  const force = hasFlag("--force");
  const concurrency = Number(process.env.CONTENT_GENERATE_CONCURRENCY ?? "3");

  const index = buildContentIndex();
  if (index.errors.length > 0) {
    console.error("Content index has errors; fix subject.json first:");
    for (const error of index.errors.slice(0, 20)) console.error(`  ${error.file}: ${error.message}`);
    process.exit(1);
  }

  /** Every subject package on disk — no hardcoded list, so a new course is picked up automatically. */
  const dirs = readdirSync(SUBJECTS_DIR).filter((entry) =>
    existsSync(path.join(SUBJECTS_DIR, entry, "subject.json")),
  );

  const jobs: Array<{ subject: Subject; topic: Topic; subtopic: Subtopic; destDir: string }> = [];
  for (const dir of dirs) {
    const subjectFile = path.join(SUBJECTS_DIR, dir, "subject.json");
    const subject = index.subjects.find((entry) => entry.id === JSON.parse(readFileSync(subjectFile, "utf8")).id);
    if (!subject) continue;
    if (only && only !== dir && only !== subject.id && only !== subject.name.toLowerCase()) continue;
    if (programme && !(subject.programmes ?? []).includes(programme)) continue;
    for (const topic of subject.topics) {
      if (year && !topic.classLevels.includes(year as (typeof topic.classLevels)[number])) continue;
      for (const subtopic of topic.subtopics) {
        jobs.push({ subject, topic, subtopic, destDir: path.join(SUBJECTS_DIR, dir) });
      }
    }
  }

  const pending = jobs.filter((job) => {
    if (force) return true;
    const folder = path.join(job.destDir, "topics", idSlug(job.topic.id));
    const slug = idSlug(job.subtopic.id);
    return !(existsSync(path.join(folder, `${slug}.lesson.json`)) && existsSync(path.join(folder, `${slug}.questions.json`)));
  });
  const queue = limit > 0 ? pending.slice(0, limit) : pending;

  console.log(`${jobs.length} subtopics in scope, ${pending.length} missing content, generating ${queue.length} (concurrency ${concurrency})`);
  if (queue.length === 0) {
    console.log("Nothing to generate.");
    return;
  }

  let wrote = 0;
  let failed = 0;
  let protectedCount = 0;
  await mapPool(queue, concurrency, async (job, index) => {
    const label = `${index + 1}/${queue.length} ${job.subtopic.id}`;
    try {
      const result = await generateOne(job.subject, job.topic, job.subtopic, job.destDir, force, questionOverride);
      if (result === "wrote") {
        wrote += 1;
        console.log(`wrote  ${label}`);
      } else if (result === "protected") {
        protectedCount += 1;
        console.log(`keep   ${label} (hand-authored, --force ignored)`);
      } else {
        console.log(`skip   ${label}`);
      }
    } catch (error) {
      failed += 1;
      console.error(`FAIL   ${label}`);
      console.error(`       ${error instanceof Error ? error.message : error}`);
    }
  });

  console.log(
    `done — wrote ${wrote}, failed ${failed}, hand-authored kept ${protectedCount}, skipped ${queue.length - wrote - failed - protectedCount}`,
  );
  if (failed > 0) process.exit(1);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
